In [6]:
import torch
import torch.nn as nn   
import torch.optim as optim

from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [7]:
datensatz = load_digits()
X = datensatz.data
y = datensatz.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# In Torch-Tensoren umwandeln
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)
y_test = torch.tensor(y_test, dtype=torch.long)
print(X_train.device)

# Einfaches neuronales Netz definieren
model1 = nn.Sequential(
        nn.Linear(64, 12),
        nn.ReLU(),
        nn.Linear(12, 10)
)

# Verlustfunktion und Optimierer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model1.parameters(), lr=0.01) # Alternativen: SGD oder Adam

# Training
epochs = 100

for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model1(X_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    
    if (epoch) % 20 == 0:
        print(f"Epoch [{epoch}/{epochs}], Loss: {loss.item():.4f}")

# Testen
with torch.no_grad():
        y_pred = model1(X_test)
        predicted = torch.argmax(y_pred, dim=1)
        #print(predicted)
        accuracy = accuracy_score(y_test, predicted)
print(f"Test Accuracy: {accuracy * 100:.2f}%")
print(confusion_matrix(y_test, predicted))



cpu
Epoch [0/100], Loss: 2.8921
Epoch [20/100], Loss: 0.6947
Epoch [40/100], Loss: 0.2061
Epoch [60/100], Loss: 0.1177
Epoch [80/100], Loss: 0.0822
Test Accuracy: 95.56%
[[31  0  1  0  1  0  0  0  0  0]
 [ 0 26  1  0  0  0  0  0  1  0]
 [ 0  1 30  1  0  0  0  0  1  0]
 [ 0  0  0 33  0  1  0  0  0  0]
 [ 0  0  0  0 46  0  0  0  0  0]
 [ 0  0  0  1  0 45  0  0  1  0]
 [ 1  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0 33  0  1]
 [ 0  1  0  0  0  1  0  0 28  0]
 [ 0  0  0  0  0  0  0  1  1 38]]


In [8]:
torch.save(model1, 'digits_modell.pth')

In [9]:
import torch
from torch import nn

# Laden des gesparten Models
modell_geladen = torch.load('digits_modell.pth',weights_only=False)
modell_geladen.eval()  # In den Evaluierungsmodus schalten

outputs = modell_geladen(X_test)

_, vorhersage = torch.max(outputs, dim=1)
# Beispiel für Genauigkeit
korrekt = (vorhersage == y_test).sum().item()
genauigkeit = korrekt / len(y_test)
print(f'Genauigkeit: {genauigkeit:.4f}')

Genauigkeit: 0.9556
